import streamlit as st
import pandas as pd
import os, hmac, subprocess

# --- 1. SYSTEM SETUP ---
@st.cache_resource
def install_playwright():
    # Installs necessary browser for the scraper on the cloud server
    subprocess.run(["playwright", "install", "chromium"])

install_playwright()

# --- 2. SUNSET THEME (Black & Orange) ---
st.markdown("""
    <style>
    .stApp { background-color: #0E1117; color: #FAFAFA; }
    [data-testid="stSidebar"] { background-color: #1c1e26; }
    .stExpander { background-color: #262730 !important; border: 1px solid #FF8C00 !important; }
    h1, h2, h3, p { color: #FAFAFA; }
    </style>
    """, unsafe_allow_html=True)

# --- 3. PASSCODE PROTECTION ---
def check_password():
    def password_entered():
        if hmac.compare_digest(st.session_state["password"], st.secrets["password"]):
            st.session_state["password_correct"] = True
            del st.session_state["password"]
        else:
            st.session_state["password_correct"] = False

    if st.session_state.get("password_correct", False):
        return True

    st.title("☀️ Patent Discovery Portal")
    st.text_input("Please enter the passcode:", type="password", on_change=password_entered, key="password")
    if "password_correct" in st.session_state:
        st.error("😕 Passcode incorrect. Please check Streamlit Secrets.")
    return False

if not check_password():
    st.stop()

# --- 4. SIDEBAR & LOGO ---
with st.sidebar:
    if os.path.exists("logo.png"):
        st.image("logo.png", use_container_width=True)
    else:
        st.title("🏢 COMPANY LOGO")
    
    st.markdown("---")
    if st.button("🚀 Run Scraper Update"):
        st.info("The scraper is running... this will generate 'master_patents.csv'.")
        # Your scraper logic would execute here and save to master_patents.csv
        st.success("Update Complete!")

# --- 5. SEARCH & QUERY INTERFACE ---
st.title("🔍 Search Patent Records")

# Load data from the CSV generated by your script
if os.path.exists("master_patents.csv"):
    df = pd.read_csv("master_patents.csv")
    
    # Create columns for a neat search layout
    col1, col2 = st.columns(2)
    
    with col1:
        q_app_num = st.text_input("Application Number")
        q_title = st.text_input("Title")
        q_abstract = st.text_input("Abstract")
        q_agent = st.text_input("Agent Name")
        q_date = st.text_input("Application Date (YYYY-MM-DD)")

    with col2:
        q_class = st.text_input("Classification")
        q_country = st.text_input("Country Name (Priority)")
        q_prio_num = st.text_input("Priority Number")
        q_prio_date = st.text_input("Priority Date (YYYY-MM-DD)")
        q_type = st.text_input("Application Type (ID)")

    # Filtering Logic for all requested fields
    filtered = df.copy()
    if q_app_num: filtered = filtered[filtered['Application Number'].astype(str).str.contains(q_app_num, case=False, na=False)]
    if q_title: filtered = filtered[filtered['Title'].str.contains(q_title, case=False, na=False)]
    if q_abstract: filtered = filtered[filtered['Abstract'].str.contains(q_abstract, case=False, na=False)]
    if q_agent: filtered = filtered[filtered['Agent Name'].str.contains(q_agent, case=False, na=False)]
    if q_date: filtered = filtered[filtered['Application Date'].astype(str).str.contains(q_date, na=False)]
    if q_class: filtered = filtered[filtered['Classification'].str.contains(q_class, case=False, na=False)]
    if q_country: filtered = filtered[filtered['Country Name (Priority)'].str.contains(q_country, case=False, na=False)]
    if q_prio_num: filtered = filtered[filtered['Priority Number'].astype(str).str.contains(q_prio_num, na=False)]
    if q_prio_date: filtered = filtered[filtered['Priority Date'].astype(str).str.contains(q_prio_date, na=False)]
    if q_type: filtered = filtered[filtered['Application Type (ID)'].astype(str).str.contains(q_type, na=False)]

    # --- 6. DISPLAY DETAILED RESULTS ---
    st.subheader(f"Results: {len(filtered)} found")
    
    for _, row in filtered.iterrows():
        with st.expander(f"📄 {row['Application Number']} - {row['Title']}"):
            res_col1, res_col2 = st.columns(2)
            with res_col1:
                st.write(f"**Application Date:** {row['Application Date']}")
                st.write(f"**Agent Name:** {row.get('Agent Name', 'N/A')}")
                st.write(f"**Classification:** {row['Classification']}")
                st.write(f"**Application Type ID:** {row['Application Type (ID)']}")
            with res_col2:
                st.write(f"**Priority Country:** {row['Country Name (Priority)']}")
                st.write(f"**Priority Number:** {row['Priority Number']}")
                st.write(f"**Priority Date:** {row['Priority Date']}")
            
            st.markdown("---")
            st.write("**Abstract:**")
            st.write(row['Abstract'] if pd.notna(row['Abstract']) else "No abstract available.")

else:
    st.warning("No data found. Please run the scraper from the sidebar or upload 'master_patents.csv' to GitHub.")
